# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170905_1923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('name', 'password')]),
        ),
    ]
